### terminal settings
# enable colors
if [ "$TERM" = "xterm" ]; then
	export TERM="xterm-color"
fi
if [ ! -z "$TMUX" ]; then
	export TERM="screen-256color"
fi

# remove binding for stop terminal (default ^S)
stty stop ''

### History control
HISTCONTROL=ignoreboth:erasedups
HISTSIZE=1024
export HISTCONTROL HISTSIZE

### Editors Preferences
export EDITOR=vim VISUAL=vim

### set PATH so it includes user's private bin if it exists
[[ -d "$HOME/bin" ]] && PATH="$HOME/bin:${PATH}"
### also includes any bin dir in current path, but less priority
PATH="${PATH}:./bin"
export PATH


### Load .bash.d/*.bash files
for file in $HOME/.bash.d/*.bash ; do
	[[ -f $file ]] && source $file
done
