set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle
" required! 
Bundle 'VundleVim/Vundle.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'tsaleh/vim-align'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-ragtag'
Bundle 'mattn/webapi-vim'
Bundle 'mattn/gist-vim'
Bundle 'mattn/emmet-vim'
Bundle 'mileszs/ack.vim'
Bundle 'elzr/vim-json'
call vundle#end()
filetype indent plugin on

""" syntax colors
syntax on
colorscheme default
set background=dark

""" set encodings
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8

""" indent, tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
set autoindent
set smartindent

""" for binary files don't change EOL
set binary
set noeol

""" temporary files on one place (stolen from sryche/vimfiles on github)
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

""" autocomplete config
set wildmode=list:longest,full

""" show mode in use (insert, visual, ...)
set showmode
set showcmd

""" mouse behavior like in terminal (without X)
set mouse=c

""" no wrap lines (duh!)
set nowrap

""" show match parentesis
set showmatch

""" statusline config
""" %y = file type
""" %t = file name
""" %l = current line
""" %c = current column
""" %V = current virtual column
""" %P = position into file
set laststatus=2
set statusline=%y\ %t\ %=\ %(%-l,%-c%-V\ %-P%)

""" show reduced msgs
set shm=filmnrwxt

""" display long lines with breaks but don't include EOL in wrap mode
set linebreak

""" fix clipboard
set clipboard=unnamed

""" some sanite mappings
cab WQ wq | cab Wq wq | cab W w | cab Q q

""" other useful mappings
nmap - :Explore<cr>

""" Filetype specific settings
au Filetype ruby set expandtab
au Filetype haml set ts=2 noet
au Filetype erb set ts=2 noet
au FileType tex set tw=78 noet spell spelllang=pt-BR
